### ISSUE TITLE
How to combine your detector with AST?

### ISSUE THREAD

**Issue by chenzhegodspeed** [lujiefsi/NPEDetector#2]
I see you use CDG CFG to do that. I  want to design a similar detector like your work but I am not sure how to get AST in this wala framework. Or this framework can only analyze .class files?

**Comment by lujiefsi** [comment]
Yes,  WALA can only analyze class file, not source code.  [WALA covert bytecode to SSA, but not covert SSA to AST](https://groups.google.com/forum/#!topic/wala-sourceforge-net/cwEWWQxDLoU).  I think you can use eclipse JDT  to get AST from source code.

**Comment by chenzhegodspeed** [comment]
So wala is same as findbugs only focus on class files? I mean is it possible to get AST from a java source code? As I known, eclipse JDT have to work in eclipse-plugin.

**Comment by lujiefsi** [comment]
Yes, in fact,  [WALA official website ](http://wala.sourceforge.net/wiki/index.php/UserGuide:Getting_Started) says it can get AST, but i never use it. you can try .

The Java front end has two implementations: one makes use of polyglot to parse Java and generate Abstract Syntax Trees (ASTs); the other is based on the Eclipse JDT and was contributed by Evan Battaglia from Berkeley. For either one, you need the following Java source language support projects, along with the CAst core and WALA core projects

**Comment by lujiefsi** [comment]
I think [polyglot ](http://www.cs.cornell.edu/projects/polyglot/) is suitable.

**Comment by chenzhegodspeed** [comment]
Thanks a lot. I will try it.

**Comment by chenzhegodspeed** [comment]
OMG! I read **UserGuide** you give me. Eclipse-JDT, this front end is suitable only for plugins. And **Ployglot** can only support Java 1.4, Java 5, and Java 7. I think it is strange without Java 8. Anyway, thanks for your guide.
