### ISSUE TITLE
The false negative problem

### ISSUE THREAD

**Issue by chenzhegodspeed** [lujiefsi/NPEDetector#3]
I see your NPE false negative case in README.md. This detector can't find it if there is a branch before NPE location? I see a class called **IntraproceduralNullPointerAnalysis** in the maven dependency. Why not use data flow analysis to solve it?

**Comment by lujiefsi** [comment]
Yes we can use data flow analysis, but need InterproceduralNullPointerAnalysis.  WALA have implement a
[Precise Interprocedural Dataflow Analysis(IFDS)](https://dl.acm.org/citation.cfm?id=199462) framework, in the next step, i want to write NPEDetector-v2 using IFDS, you can also try it.

**Comment by lujiefsi** [comment]
In our initial implementation, in fact we dost not apply CDG, we only check if there exist a null checker in caller, if exist, we think this caller won't cause NPE. This must cause some false negative, but little,

**Comment by lujiefsi** [comment]
One more thing, findbugs also have IntraproceduralNullPointerAnalysis rule
