### ISSUE TITLE
Complex detection

### ISSUE THREAD

**Issue by april1989** [lujiefsi/NPEDetector#5]
Simple but effective implementation! 

I have a question about the complex detection: when you check all use instructions controlled by check null condition(CNC), the checked instructions are within the caller method? No checking of the caller's caller method? Thanks.

**Comment by april1989** [comment]
BTW, there is another NPEDetector published in "Null Dereference Verification via Overapproximated Weakest Pre-conditions Analysis", which use inter-procedure analysis, maybe you wanner have a try.

**Comment by lujiefsi** [comment]
HI: @april1989 
`No checking of the caller's caller method`
Yes, no checking for the caller's caller method, we develop this tool based on our observation from real word NPE bugs, we find that most of them are very simple. hence we only check the caller method, We must miss some deep bugs. And i am trying to use another NPEDetector.
Thanks.
