### ISSUE TITLE
Where to get a reproducible bug to get start?

### ISSUE THREAD

**Issue by QRXqrx** [lujiefsi/NPEDetector#7]
Hi, 

I noticed the cmd in your `Readme`, but I have no idea where to get a input project like that( `-inputDir /home/lujie/tmp`). Would you mind giving me any simple example at your convinience? A link for downloading such projects is ok, too. 

Thanks :-)

**Comment by lujiefsi** [comment]
https://archive.apache.org/dist/hadoop/core/
https://archive.apache.org/dist/hbase/
https://archive.apache.org/dist/cloudstack/

 you also can check https://archive.apache.org/dist/  to find other proejct jar
